baseURL = "https://bernhardtd.github.io/"
title = "Tech Vanguard"
copyright = "This work is licensed under a <a rel=\"license\" href=\"http://creativecommons.org/licenses/by-sa/4.0/\">Creative Commons Attribution-ShareAlike 4.0 International License</a>."
theme = "chunky-poster"
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
# googleAnalytics = "UA-XXXX"
DisqusShortname = ""

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Daniel Bernhardt"
  description = "be creative and meet challenges..."
  homepageImage = "/images/homepage-image.jpg"
  share = true
  showLanguageSwitcher = false

  [params.social]
    rss = true
    # email = "example@example.com"
    facebook = "https://www.facebook.com/danielbernhardt42"
    twitter = "https://twitter.com/BernhardtD42"
    linkedin = "https://www.linkedin.com/in/danielbernhardt42/"
    # stack-overflow = "https://stackoverflow.com"
    # instagram = "https://stackoverflow.com"
    github = "https://github.com/BernhardtD"
    # weibo = "https://www.weibo.com"
    # medium = "https://medium.com"
    # pinterest = "https://pinterest.com"
    # reddit = "https://reddit.com"
    # gitlab = "https://gitlab.com"
    # mastodon = "https://mastodon.social"
    # keybase = "https://keybase.io/"

  [params.prismJS]
    enable = false
    theme = ""

  [params.commento]
    enable = false
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[markup.goldmark.renderer]
unsafe= true

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
